[package]
name = "autogit"
version = "0.2.0"
authors = ["Finn K <fyndalf@users.noreply.github.com>"]
edition = "2018"

[dependencies]
quicli= "0.4.0"
structopt = "0.2.16"
git2 = "0.9.1"
human-panic = "1.0.1"
console = "0.7.7"
indicatif = "0.11.0"
